# Generated by Django 4.0.3 on 2022-03-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('identification_no', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('parchase_date', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_address', models.CharField(max_length=100)),
                ('warrenty', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('office_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
            ],
        ),
    ]
