# Generated by Django 4.0.3 on 2022-03-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories_name', models.CharField(blank=True, max_length=100, null=True)),
                ('identification_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('accessories_supplier_name_address', models.CharField(blank=True, max_length=100, null=True)),
                ('warrenty', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('office_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=100, null=True)),
                ('is_assign', models.BooleanField(default=False)),
                ('is_condem', models.BooleanField(default=False)),
            ],
        ),
    ]
