# Generated by Django 4.0.3 on 2022-03-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_alter_accessories_is_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='is_assign',
            field=models.CharField(blank=True, default='no', max_length=100, null=True),
        ),
    ]
