# Generated by Django 4.0.3 on 2022-03-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_alter_accessories_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='item_name',
            new_name='accessories_name',
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='parchase_date',
            new_name='accessories_supplier_name_address',
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='supplier_address',
            new_name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='supplier_name',
        ),
    ]
