# Generated by Django 4.0.3 on 2022-03-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_rename_item_name_accessories_accessories_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='is_assign',
            field=models.BooleanField(default=False),
        ),
    ]
