# Generated by Django 4.0.3 on 2022-03-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_alter_accessories_is_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='is_assign',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='is_condem',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
