# Generated by Django 4.0.3 on 2022-03-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0004_accessories_is_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='is_assign',
            field=models.BooleanField(default=True),
        ),
    ]
