# Generated by Django 4.0.3 on 2022-03-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0005_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
