# Generated by Django 4.0.3 on 2022-03-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0005_alter_accessories_is_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='is_condem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='is_assign',
            field=models.BooleanField(default=False),
        ),
    ]
